/**
 * CSS变量工具
 *
 * 这个文件由export-css-vars.js自动生成，请勿直接修改
 */

// 所有CSS变量
export const CSS_VARS: Record<string, string> = {
  '--bn-bg-default': '#{$bg-default}',
  '--bn-bg-secondary': '#{$bg-secondary}',
  '--bn-bg-tertiary': '#{$bg-tertiary}',
  '--bn-bg-disabled': '#{$bg-disabled}',
  '--bn-bg-inverse': '#{$bg-inverse}',
  '--bn-bg-primary': '#{$bg-primary}',
  '--bn-bg-success': '#{$bg-success}',
  '--bn-bg-warning': '#{$bg-warning}',
  '--bn-bg-danger': '#{$bg-danger}',
  '--bn-bg-info': '#{$bg-info}',
  '--bn-bg-primary-dark': '#{$bg-primary-dark}',
  '--bn-bg-success-dark': '#{$bg-success-dark}',
  '--bn-bg-warning-dark': '#{$bg-warning-dark}',
  '--bn-bg-danger-dark': '#{$bg-danger-dark}',
  '--bn-bg-info-dark': '#{$bg-info-dark}',
  '--bn-bg-highlight': '#{$bg-highlight}',
  '--bn-bg-selected': '#{$bg-selected}',
  '--bn-bg-active': '#{$bg-active}',
  '--bn-bg-hover': 'rgba(255, 255, 255, 0.1)',
  '--bn-bg-hover-light': 'rgba(255, 255, 255, 0.05)',
  '--bn-bg-mask': '#{$bg-mask}',
  '--bn-bg-overlay': '#{$bg-overlay}',
  '--bn-bg-backdrop': '#{$bg-backdrop}',
  '--bn-bg-translucent-light': '#{$bg-translucent-light}',
  '--bn-bg-translucent-dark': '#{$bg-translucent-dark}',
  '--bn-bg-gradient-primary': '#{$bg-gradient-primary}',
  '--bn-bg-gradient-success': '#{$bg-gradient-success}',
  '--bn-bg-gradient-warning': '#{$bg-gradient-warning}',
  '--bn-bg-gradient-danger': '#{$bg-gradient-danger}',
  '--bn-bg-gradient-info': '#{$bg-gradient-info}',
  '--bn-bg-stripe-light': '#{$bg-stripe-light}',
  '--bn-bg-stripe-dark': '#{$bg-stripe-dark}',
  '--bn-border-color': '#{$border-color}',
  '--bn-border-color-light': '#{$border-color-light}',
  '--bn-border-color-dark': '#{$border-color-dark}',
  '--bn-border-color-disabled': '#{$border-color-disabled}',
  '--bn-border-color-inverse': '#{$border-color-inverse}',
  '--bn-border-color-primary': '#{$border-color-primary}',
  '--bn-border-color-success': '#{$border-color-success}',
  '--bn-border-color-warning': '#{$border-color-warning}',
  '--bn-border-color-danger': '#{$border-color-danger}',
  '--bn-border-color-info': '#{$border-color-info}',
  '--bn-border-color-primary-light': '#{$border-color-primary-light}',
  '--bn-border-color-success-light': '#{$border-color-success-light}',
  '--bn-border-color-warning-light': '#{$border-color-warning-light}',
  '--bn-border-color-danger-light': '#{$border-color-danger-light}',
  '--bn-border-color-info-light': '#{$border-color-info-light}',
  '--bn-border-color-primary-dark': '#{$border-color-primary-dark}',
  '--bn-border-color-success-dark': '#{$border-color-success-dark}',
  '--bn-border-color-warning-dark': '#{$border-color-warning-dark}',
  '--bn-border-color-danger-dark': '#{$border-color-danger-dark}',
  '--bn-border-color-info-dark': '#{$border-color-info-dark}',
  '--bn-border-width-none': '#{$border-width-none}',
  '--bn-border-width-xs': '#{$border-width-xs}',
  '--bn-border-width-sm': '#{$border-width-sm}',
  '--bn-border-width-md': '#{$border-width-md}',
  '--bn-border-width-lg': '#{$border-width-lg}',
  '--bn-border-style-solid': '#{$border-style-solid}',
  '--bn-border-style-dashed': '#{$border-style-dashed}',
  '--bn-border-style-dotted': '#{$border-style-dotted}',
  '--bn-border-style-double': '#{$border-style-double}',
  '--bn-border-style-groove': '#{$border-style-groove}',
  '--bn-border-style-ridge': '#{$border-style-ridge}',
  '--bn-border-style-inset': '#{$border-style-inset}',
  '--bn-border-style-outset': '#{$border-style-outset}',
  '--bn-border-radius-none': '#{$border-radius-none}',
  '--bn-border-radius-xs': '#{$border-radius-xs}',
  '--bn-border-radius-sm': '#{$border-radius-sm}',
  '--bn-border-radius-md': '#{$border-radius-md}',
  '--bn-border-radius-lg': '#{$border-radius-lg}',
  '--bn-border-radius-xl': '#{$border-radius-xl}',
  '--bn-border-radius-full': '#{$border-radius-full}',
  '--bn-border-radius-circle': '#{$border-radius-circle}',
  '--bn-border-shadow-xs': '0 0 0 1px rgba(255, 255, 255, 0.05)',
  '--bn-border-shadow-sm': '0 0 0 1px rgba(255, 255, 255, 0.1)',
  '--bn-border-shadow-md': '0 0 0 2px rgba(255, 255, 255, 0.1)',
  '--bn-border-shadow-lg': '0 0 0 4px rgba(255, 255, 255, 0.1)',
  '--bn-border-shadow-primary': '#{$border-shadow-primary}',
  '--bn-border-shadow-success': '#{$border-shadow-success}',
  '--bn-border-shadow-warning': '#{$border-shadow-warning}',
  '--bn-border-shadow-danger': '#{$border-shadow-danger}',
  '--bn-border-shadow-info': '#{$border-shadow-info}',
  '--bn-glow-primary': '#{$glow-primary}',
  '--bn-glow-success': '#{$glow-success}',
  '--bn-glow-warning': '#{$glow-warning}',
  '--bn-glow-danger': '#{$glow-danger}',
  '--bn-glow-info': '#{$glow-info}',
  '--bn-blur-none': '#{$blur-none}',
  '--bn-blur-sm': '#{$blur-sm}',
  '--bn-blur-md': '#{$blur-md}',
  '--bn-blur-lg': '#{$blur-lg}',
  '--bn-blur-xl': '#{$blur-xl}',
  '--bn-filter-none': '#{$filter-none}',
  '--bn-filter-grayscale': '#{$filter-grayscale}',
  '--bn-filter-sepia': '#{$filter-sepia}',
  '--bn-filter-saturate': '#{$filter-saturate}',
  '--bn-filter-invert': '#{$filter-invert}',
  '--bn-filter-brightness-low': '#{$filter-brightness-low}',
  '--bn-filter-brightness-high': '#{$filter-brightness-high}',
  '--bn-filter-contrast-low': '#{$filter-contrast-low}',
  '--bn-filter-contrast-high': '#{$filter-contrast-high}',
  '--bn-font-family-sans-serif': '#{inspect($font-family-sans-serif)}',
  '--bn-font-family-monospace': '#{inspect($font-family-monospace)}',
  '--bn-font-family-chinese': '#{inspect($font-family-chinese)}',
  '--bn-font-family-base': 'var(--bn-font-family-sans-serif)',
  '--bn-font-size-base': '#{$font-size-base}',
  '--bn-font-size-xs': '#{$font-size-xs}',
  '--bn-font-size-sm': '#{$font-size-sm}',
  '--bn-font-size-md': '#{$font-size-md}',
  '--bn-font-size-lg': '#{$font-size-lg}',
  '--bn-font-size-xl': '#{$font-size-xl}',
  '--bn-h1-font-size': '#{$h1-font-size}',
  '--bn-h2-font-size': '#{$h2-font-size}',
  '--bn-h3-font-size': '#{$h3-font-size}',
  '--bn-h4-font-size': '#{$h4-font-size}',
  '--bn-h5-font-size': '#{$h5-font-size}',
  '--bn-h6-font-size': '#{$h6-font-size}',
  '--bn-font-weight-lighter': '#{$font-weight-lighter}',
  '--bn-font-weight-light': '#{$font-weight-light}',
  '--bn-font-weight-normal': '#{$font-weight-normal}',
  '--bn-font-weight-medium': '#{$font-weight-medium}',
  '--bn-font-weight-semibold': '#{$font-weight-semibold}',
  '--bn-font-weight-bold': '#{$font-weight-bold}',
  '--bn-font-weight-bolder': '#{$font-weight-bolder}',
  '--bn-font-weight-base': 'var(--bn-font-weight-normal)',
  '--bn-font-weight-headings': 'var(--bn-font-weight-medium)',
  '--bn-letter-spacing-tighter': '#{$letter-spacing-tighter}',
  '--bn-letter-spacing-tight': '#{$letter-spacing-tight}',
  '--bn-letter-spacing-normal': '#{$letter-spacing-normal}',
  '--bn-letter-spacing-wide': '#{$letter-spacing-wide}',
  '--bn-letter-spacing-wider': '#{$letter-spacing-wider}',
  '--bn-letter-spacing-widest': '#{$letter-spacing-widest}',
  '--bn-h1-size': '#{$h1-font-size}',
  '--bn-h2-size': '#{$h2-font-size}',
  '--bn-h3-size': '#{$h3-font-size}',
  '--bn-h4-size': '#{$h4-font-size}',
  '--bn-h5-size': '#{$h5-font-size}',
  '--bn-h6-size': '#{$h6-font-size}',
  '--bn-h1-weight': '#{$h1-font-weight}',
  '--bn-h2-weight': '#{$h2-font-weight}',
  '--bn-h3-weight': '#{$h3-font-weight}',
  '--bn-h4-weight': '#{$h4-font-weight}',
  '--bn-h5-weight': '#{$h5-font-weight}',
  '--bn-h6-weight': '#{$h6-font-weight}',
  '--bn-h1-line-height': '#{$h1-line-height}',
  '--bn-h2-line-height': '#{$h2-line-height}',
  '--bn-h3-line-height': '#{$h3-line-height}',
  '--bn-h4-line-height': '#{$h4-line-height}',
  '--bn-h5-line-height': '#{$h5-line-height}',
  '--bn-h6-line-height': '#{$h6-line-height}',
  '--bn-h1-color': 'var(--bn-neutral-1)',
  '--bn-h2-color': 'var(--bn-neutral-1)',
  '--bn-h3-color': 'var(--bn-neutral-1)',
  '--bn-h4-color': 'var(--bn-neutral-1)',
  '--bn-h5-color': 'var(--bn-neutral-1)',
  '--bn-h6-color': 'var(--bn-neutral-1)',
  '--bn-h1-letter-spacing': '#{$h1-letter-spacing}',
  '--bn-h2-letter-spacing': '#{$h2-letter-spacing}',
  '--bn-h3-letter-spacing': '#{$h3-letter-spacing}',
  '--bn-h4-letter-spacing': '#{$h4-letter-spacing}',
  '--bn-h5-letter-spacing': '#{$h5-letter-spacing}',
  '--bn-h6-letter-spacing': '#{$h6-letter-spacing}',
  '--bn-heading-font-family': '#{$heading-font-family}',
  '--bn-heading-border-bottom-width': '#{$heading-border-bottom-width}',
  '--bn-heading-border-bottom-style': '#{$heading-border-bottom-style}',
  '--bn-heading-border-bottom-color': 'var(--bn-neutral-7)',
  '--bn-heading-badge-font-size': '#{$heading-badge-font-size}',
  '--bn-heading-badge-padding': '#{$heading-badge-padding}',
  '--bn-heading-badge-border-radius': '#{$heading-badge-border-radius}',
  '--bn-heading-badge-background': 'var(--bn-primary-9)',
  '--bn-heading-badge-color': 'var(--bn-primary-3)',
  '--bn-heading-badge-margin-left': '#{$heading-badge-margin-left}',
  '--bn-heading-hover-color': 'var(--bn-primary-4)',
  '--bn-opacity-0': '#{$opacity-0}',
  '--bn-opacity-5': '#{$opacity-5}',
  '--bn-opacity-10': '#{$opacity-10}',
  '--bn-opacity-20': '#{$opacity-20}',
  '--bn-opacity-25': '#{$opacity-25}',
  '--bn-opacity-30': '#{$opacity-30}',
  '--bn-opacity-40': '#{$opacity-40}',
  '--bn-opacity-50': '#{$opacity-50}',
  '--bn-opacity-60': '#{$opacity-60}',
  '--bn-opacity-70': '#{$opacity-70}',
  '--bn-opacity-75': '#{$opacity-75}',
  '--bn-opacity-80': '#{$opacity-80}',
  '--bn-opacity-90': '#{$opacity-90}',
  '--bn-opacity-95': '#{$opacity-95}',
  '--bn-opacity-100': '#{$opacity-100}',
  '--bn-breakpoint-xs': '#{$viewport-xs}',
  '--bn-breakpoint-sm': '#{$viewport-sm}',
  '--bn-breakpoint-md': '#{$viewport-md}',
  '--bn-breakpoint-lg': '#{$viewport-lg}',
  '--bn-breakpoint-xl': '#{$viewport-xl}',
  '--bn-breakpoint-xxl': '#{$viewport-xxl}',
  '--bn-grid-columns': '#{$grid-columns}',
  '--bn-grid-gutter-width': '#{$grid-gutter-width}',
  '--bn-grid-row-columns': '#{$grid-row-columns}',
  '--bn-responsive-font-breakpoint': '#{$responsive-font-breakpoint}',
  '--bn-responsive-spacing-breakpoint': '#{$responsive-spacing-breakpoint}',
  '--bn-responsive-font-scale-mobile': '#{$responsive-font-scale-mobile}',
  '--bn-responsive-font-scale-tablet': '#{$responsive-font-scale-tablet}',
  '--bn-responsive-font-scale-desktop': '#{$responsive-font-scale-desktop}',
  '--bn-responsive-spacing-scale-mobile': '#{$responsive-spacing-scale-mobile}',
  '--bn-responsive-spacing-scale-tablet': '#{$responsive-spacing-scale-tablet}',
  '--bn-responsive-spacing-scale-desktop': '#{$responsive-spacing-scale-desktop}',
  '--bn-shadow-color': '#{$shadow-color}',
  '--bn-shadow-color-light': 'rgba(0, 0, 0, 0.25)',
  '--bn-shadow-color-dark': 'rgba(0, 0, 0, 0.75)',
  '--bn-shadow-none': '#{$shadow-none}',
  '--bn-shadow-xs': '#{$shadow-xs}',
  '--bn-shadow-sm': '#{$shadow-sm}',
  '--bn-shadow-md': '#{$shadow-md}',
  '--bn-shadow-lg': '#{$shadow-lg}',
  '--bn-shadow-xl': '#{$shadow-xl}',
  '--bn-shadow-2xl': '#{$shadow-2xl}',
  '--bn-shadow-inner': '#{$shadow-inner}',
  '--bn-shadow-top': '#{$shadow-top}',
  '--bn-shadow-right': '#{$shadow-right}',
  '--bn-shadow-bottom': '#{$shadow-bottom}',
  '--bn-shadow-left': '#{$shadow-left}',
  '--bn-size-unit': '#{$size-unit}',
  '--bn-spacing-0': '#{$spacing-0}',
  '--bn-spacing-1': '#{$spacing-1}',
  '--bn-spacing-2': '#{$spacing-2}',
  '--bn-spacing-3': '#{$spacing-3}',
  '--bn-spacing-4': '#{$spacing-4}',
  '--bn-spacing-5': '#{$spacing-5}',
  '--bn-spacing-6': '#{$spacing-6}',
  '--bn-spacing-8': '#{$spacing-8}',
  '--bn-spacing-10': '#{$spacing-10}',
  '--bn-spacing-12': '#{$spacing-12}',
  '--bn-spacing-16': '#{$spacing-16}',
  '--bn-spacing-20': '#{$spacing-20}',
  '--bn-spacing-24': '#{$spacing-24}',
  '--bn-spacing-32': '#{$spacing-32}',
  '--bn-spacing-40': '#{$spacing-40}',
  '--bn-spacing-48': '#{$spacing-48}',
  '--bn-spacing-56': '#{$spacing-56}',
  '--bn-spacing-64': '#{$spacing-64}',
  '--bn-spacing-n1': '#{$spacing-n1}',
  '--bn-spacing-n2': '#{$spacing-n2}',
  '--bn-spacing-n3': '#{$spacing-n3}',
  '--bn-spacing-n4': '#{$spacing-n4}',
  '--bn-spacing-n6': '#{$spacing-n6}',
  '--bn-spacing-n8': '#{$spacing-n8}',
  '--bn-spacing-n12': '#{$spacing-n12}',
  '--bn-spacing-n16': '#{$spacing-n16}',
  '--bn-width-1': '#{$width-1}',
  '--bn-width-2': '#{$width-2}',
  '--bn-width-3': '#{$width-3}',
  '--bn-width-4': '#{$width-4}',
  '--bn-width-5': '#{$width-5}',
  '--bn-width-6': '#{$width-6}',
  '--bn-width-7': '#{$width-7}',
  '--bn-width-8': '#{$width-8}',
  '--bn-width-9': '#{$width-9}',
  '--bn-width-10': '#{$width-10}',
  '--bn-width-11': '#{$width-11}',
  '--bn-width-12': '#{$width-12}',
  '--bn-height-1-2': '#{$height-1-2}',
  '--bn-height-1-3': '#{$height-1-3}',
  '--bn-height-2-3': '#{$height-2-3}',
  '--bn-height-1-4': '#{$height-1-4}',
  '--bn-height-3-4': '#{$height-3-4}',
  '--bn-height-1-5': '#{$height-1-5}',
  '--bn-height-2-5': '#{$height-2-5}',
  '--bn-height-3-5': '#{$height-3-5}',
  '--bn-height-4-5': '#{$height-4-5}',
  '--bn-height-full': '#{$height-full}',
  '--bn-height-screen': '#{$height-screen}',
  '--bn-max-width-none': '#{$max-width-none}',
  '--bn-max-width-xs': '#{$max-width-xs}',
  '--bn-max-width-sm': '#{$max-width-sm}',
  '--bn-max-width-md': '#{$max-width-md}',
  '--bn-max-width-lg': '#{$max-width-lg}',
  '--bn-max-width-xl': '#{$max-width-xl}',
  '--bn-max-width-2xl': '#{$max-width-2xl}',
  '--bn-max-width-full': '#{$max-width-full}',
  '--bn-spacer': '#{$spacer}',
  '--bn-layout-spacing-xs': '#{$layout-spacing-xs}',
  '--bn-layout-spacing-sm': '#{$layout-spacing-sm}',
  '--bn-layout-spacing-md': '#{$layout-spacing-md}',
  '--bn-layout-spacing-lg': '#{$layout-spacing-lg}',
  '--bn-layout-spacing-xl': '#{$layout-spacing-xl}',
  '--bn-padding-xs': '#{$padding-xs}',
  '--bn-padding-sm': '#{$padding-sm}',
  '--bn-padding-md': '#{$padding-md}',
  '--bn-padding-lg': '#{$padding-lg}',
  '--bn-padding-xl': '#{$padding-xl}',
  '--bn-margin-xs': '#{$margin-xs}',
  '--bn-margin-sm': '#{$margin-sm}',
  '--bn-margin-md': '#{$margin-md}',
  '--bn-margin-lg': '#{$margin-lg}',
  '--bn-margin-xl': '#{$margin-xl}',
  '--bn-text-color': '#{$text-color}',
  '--bn-text-color-secondary': '#{$text-color-secondary}',
  '--bn-text-color-disabled': '#{$text-color-disabled}',
  '--bn-text-color-inverse': '#{$text-color-inverse}',
  '--bn-text-shadow-sm': '#{$text-shadow-sm}',
  '--bn-text-shadow-md': '#{$text-shadow-md}',
  '--bn-text-shadow-lg': '#{$text-shadow-lg}',
  '--bn-line-height-none': '#{$line-height-none}',
  '--bn-line-height-tight': '#{$line-height-tight}',
  '--bn-line-height-snug': '#{$line-height-snug}',
  '--bn-line-height-normal': '#{$line-height-normal}',
  '--bn-line-height-relaxed': '#{$line-height-relaxed}',
  '--bn-line-height-loose': '#{$line-height-loose}',
  '--bn-mark-background-color': 'var(--bn-warning-9)',
  '--bn-mark-color': 'var(--bn-warning-1)',
  '--bn-transition-none': '#{$transition-none}',
  '--bn-transition-slow': '#{$transition-slow}',
  '--bn-transition-normal': '#{$transition-normal}',
  '--bn-transition-fast': '#{$transition-fast}',
  '--bn-transition-opacity': '#{$transition-opacity}',
  '--bn-transition-colors': '#{$transition-colors}',
  '--bn-transition-shadow': '#{$transition-shadow}',
  '--bn-transition-transform': '#{$transition-transform}',
  '--bn-ease-linear': '#{$ease-linear}',
  '--bn-ease-in': '#{$ease-in}',
  '--bn-ease-out': '#{$ease-out}',
  '--bn-ease-in-out': '#{$ease-in-out}',
  '--bn-ease-bounce': '#{$ease-bounce}',
  '--bn-z-index-0': '#{$z-index-0}',
  '--bn-z-index-10': '#{$z-index-10}',
  '--bn-z-index-20': '#{$z-index-20}',
  '--bn-z-index-30': '#{$z-index-30}',
  '--bn-z-index-40': '#{$z-index-40}',
  '--bn-z-index-50': '#{$z-index-50}',
  '--bn-z-index-100': '#{$z-index-100}',
  '--bn-z-index-200': '#{$z-index-200}',
  '--bn-z-index-500': '#{$z-index-500}',
  '--bn-z-index-1000': '#{$z-index-1000}',
  '--bn-z-index-floating': '#{$z-index-floating}',
  '--bn-z-index-modal': '#{$z-index-modal}',
  '--bn-z-index-popover': '#{$z-index-popover}',
  '--bn-z-index-tooltip': '#{$z-index-tooltip}',
  '--bn-z-index-overlay': '#{$z-index-overlay}',
  '--bn-z-index-dropdown': '#{$z-index-dropdown}',
  '--bn-z-index-header': '#{$z-index-header}',
  '--bn-z-index-footer': '#{$z-index-footer}',
  '--bn-z-index-sticky': '#{$z-index-sticky}',
  '--bn-z-index-fixed': '#{$z-index-fixed}',
  '--bn-blockquote-padding-left': '#{$blockquote-padding-left}',
  '--bn-blockquote-border-width': '#{$blockquote-border-width}',
  '--bn-blockquote-border-color': 'var(--bn-primary-6)',
  '--bn-blockquote-font-style': '#{$blockquote-font-style}',
  '--bn-blockquote-color': 'var(--bn-neutral-3)',
  '--bn-button-padding-y-xs': '#{$button-padding-y-xs}',
  '--bn-button-padding-x-xs': '#{$button-padding-x-xs}',
  '--bn-button-padding-y-sm': '#{$button-padding-y-sm}',
  '--bn-button-padding-x-sm': '#{$button-padding-x-sm}',
  '--bn-button-padding-y-md': '#{$button-padding-y-md}',
  '--bn-button-padding-x-md': '#{$button-padding-x-md}',
  '--bn-button-padding-y-lg': '#{$button-padding-y-lg}',
  '--bn-button-padding-x-lg': '#{$button-padding-x-lg}',
  '--bn-button-padding-y-xl': '#{$button-padding-y-xl}',
  '--bn-button-padding-x-xl': '#{$button-padding-x-xl}',
  '--bn-code-font-family': '#{$code-font-family}',
  '--bn-code-font-size': '#{$code-font-size}',
  '--bn-code-color': 'var(--bn-danger-3)',
  '--bn-code-background-color': 'var(--bn-neutral-8)',
  '--bn-code-padding': '#{$code-padding}',
  '--bn-code-border-radius': '#{$code-border-radius}',
  '--bn-component-size-xs': '#{$component-size-xs}',
  '--bn-component-size-sm': '#{$component-size-sm}',
  '--bn-component-size-md': '#{$component-size-md}',
  '--bn-component-size-lg': '#{$component-size-lg}',
  '--bn-component-size-xl': '#{$component-size-xl}',
  '--bn-component-spacing-xs': '#{$component-spacing-xs}',
  '--bn-component-spacing-sm': '#{$component-spacing-sm}',
  '--bn-component-spacing-md': '#{$component-spacing-md}',
  '--bn-component-spacing-lg': '#{$component-spacing-lg}',
  '--bn-component-spacing-xl': '#{$component-spacing-xl}',
  '--bn-control-padding-xs': '#{$control-padding-xs}',
  '--bn-control-padding-sm': '#{$control-padding-sm}',
  '--bn-control-padding-md': '#{$control-padding-md}',
  '--bn-control-padding-lg': '#{$control-padding-lg}',
  '--bn-control-padding-xl': '#{$control-padding-xl}',
  '--bn-form-group-margin-bottom': '#{$form-group-margin-bottom}',
  '--bn-form-label-margin-bottom': '#{$form-label-margin-bottom}',
  '--bn-form-input-padding-y': '#{$form-input-padding-y}',
  '--bn-form-input-padding-x': '#{$form-input-padding-x}',
  '--bn-icon-size-xs': '#{$icon-size-xs}',
  '--bn-icon-size-sm': '#{$icon-size-sm}',
  '--bn-icon-size-md': '#{$icon-size-md}',
  '--bn-icon-size-lg': '#{$icon-size-lg}',
  '--bn-icon-size-xl': '#{$icon-size-xl}',
  '--bn-link-color': 'var(--bn-primary-3)',
  '--bn-link-color-hover': 'var(--bn-primary-2)',
  '--bn-link-color-active': 'var(--bn-primary-1)',
  '--bn-link-color-visited': 'var(--bn-primary-4)',
  '--bn-navbar-mobile-breakpoint': '#{$navbar-mobile-breakpoint}',
  '--bn-z-index-navbar': '#{$z-index-navbar}',
  '--bn-scrollbar-width': '#{$scrollbar-width}',
  '--bn-scrollbar-height': '#{$scrollbar-height}',
  '--bn-scrollbar-min-size': '#{$scrollbar-min-size}',
  '--bn-scrollbar-track-color': 'var(--bn-neutral-8)',
  '--bn-scrollbar-thumb-color': 'var(--bn-neutral-6)',
  '--bn-scrollbar-thumb-hover-color': 'var(--bn-neutral-5)',
  '--bn-scrollbar-thumb-active-color': 'var(--bn-neutral-4)',
  '--bn-scrollbar-border-radius': '#{$scrollbar-border-radius}',
  '--bn-selection-background-color': 'var(--bn-primary-8)',
  '--bn-selection-color': 'var(--bn-primary-2)',
  '--bn-sidebar-breakpoint': '#{$sidebar-breakpoint}',
  '--bn-z-index-sidebar': '#{$z-index-sidebar}',
  '--bn-neutral-bg-primary': 'var(--bn-neutral-9)',
  '--bn-neutral-bg-secondary': 'var(--bn-neutral-8)',
  '--bn-neutral-bg-tertiary': 'var(--bn-neutral-7)',
  '--bn-neutral-bg-disabled': 'var(--bn-neutral-6)',
  '--bn-neutral-bg-inverse': 'var(--bn-neutral-1)',
  '--bn-neutral-text-primary': 'var(--bn-neutral-1)',
  '--bn-neutral-text-secondary': 'var(--bn-neutral-3)',
  '--bn-neutral-text-disabled': 'var(--bn-neutral-6)',
  '--bn-neutral-text-inverse': 'var(--bn-neutral-9)',
  '--bn-neutral-border-primary': 'var(--bn-neutral-6)',
  '--bn-neutral-border-secondary': 'var(--bn-neutral-7)',
  '--bn-neutral-border-disabled': 'var(--bn-neutral-8)',
  '--bn-neutral-shadow': 'rgba(0, 0, 0, 0.65)'
}

/**
 * 获取所有CSS变量
 * @returns 所有CSS变量对象
 */
export function getAllCssVars(): Record<string, string> {
  return CSS_VARS
}

/**
 * 获取特定类别的CSS变量
 * @param category 变量类别，如'color', 'spacing'等
 * @returns 指定类别的CSS变量对象
 */
export function getCategoryVars(category: string): Record<string, string> {
  const result: Record<string, string> = {}
  const prefix = `--${category}-`

  Object.entries(CSS_VARS).forEach(([key, value]) => {
    if (key.startsWith(prefix)) {
      result[key] = value
    }
  })

  return result
}

/**
 * 获取CSS变量值
 * @param name 变量名称，不含--前缀
 * @returns CSS变量值
 */
export function getCssVar(name: string): string | undefined {
  const key = name.startsWith('--') ? name : `--${name}`
  return CSS_VARS[key]
}

/**
 * 获取当前主题下的实际CSS变量值
 * 从文档中读取实际计算后的CSS变量值
 * @param name 变量名称，需要包含--前缀
 * @returns 计算后的CSS变量值
 */
export function getComputedCssVar(name: string): string {
  const key = name.startsWith('--') ? name : `--${name}`
  if (typeof document === 'undefined') return ''
  return getComputedStyle(document.documentElement).getPropertyValue(key).trim()
}
